#!/usr/sbin/nft -f
flush ruleset

define LAN4 = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 169.254.0.0/16 }
define LAN6 = { fe80::/10, fc00::/7 }

table inet smartboard {
  chain input {
    type filter hook input priority filter; policy drop;
    iif lo accept
    ct state established,related accept
    ct state invalid drop
    meta l4proto { icmp, ipv6-icmp } accept
    udp sport 67 udp dport 68 accept
    udp sport 547 udp dport 546 accept
    udp dport 5353 accept
    ip saddr $LAN4 tcp dport { 22, 80, 8080 } accept
    ip6 saddr $LAN6 tcp dport { 22, 80, 8080 } accept
  }
  chain forward {
    type filter hook forward priority filter; policy drop;
  }
  chain prerouting {
    type nat hook prerouting priority dstnat;
    tcp dport 80 redirect to :8080
  }
}
